services:
  - type: web
    name: freshdesk-afj-global
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn freshdesk_server:app
    envVars:
      - key: FRESHDESK_DOMAIN
        value: consultame
      - key: FRESHDESK_API_KEY
        value: 6egUChwBAUA2633n18DC
      - key: PYTHON_VERSION
        value: 3.11.0
